### ISSUE TITLE
CUDA error when train on custom dataset

### ISSUE THREAD

**Issue by helia-mohamadi** [GiovanniPasq/DA-Faster-RCNN#6]
Hello 
I use your model and code for my own dataset, but when I trained that I've got this error :

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by GiovanniPasq** [comment]
HI,
searching on the internet it seems that the problem is related to the labels of your dataset. Can you check if they are correct?
I found a similar problem on stackoverflow, please check this link and let me know:

https://stackoverflow.com/questions/68166721/cuda-error-device-side-assert-triggered-on-colab

**Comment by TahereSaidi** [comment]
Hi
After I fixed the addressing error, I encountered this error. I used the CPU, but it didn't help. I also used restart and disconnect. Surely the problem is with the classes. Can you tell me in which file we should specify the number of classes?

**Comment by helia2078** [comment]
Thank you for answering
Yes, my labels are different from the model labels (my source, target and test labels are also different to each other)
In which part of the script code can I customize the labels for my data?

**Comment by helia-mohamadi** [comment]
Thank you for answering
Yes, my labels are different from the model labels (I have 5 classes)
In which part of the script code can I customize the class labels for my data?
I've tried to change it in " cfg_source.MODEL.ROI_HEADS.NUM_CLASSES " , but I got the same error
I also checked the ROI_HEADS.py , but I couldn't fix that. 
Could you please guide me in this matter?

**Comment by GiovanniPasq** [comment]
If you have 5 classes is correct to set the roi heads to 5 as you have done.
```
cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 5
```

However the error is related to your annotations. Are you sure the labels go from 0 to 4?

**Comment by helia-mohamadi** [comment]
Thank you 
I changed it then restart the runtime and run again
this process fixed my problem

**Comment by helia2078** [comment]
Hello again

**Comment by helia2078** [comment]
Hello again 
I wanted to ask you about how to optimize your model compared to the original model and what changes compared to the original source code that have improved the process.
thank you
